url_profile = 'https://github.com/saypinkx/HackHunter'
url_whois = 'https://github.com/saypinkx/HackHunter'
url_hunt = 'https://github.com/saypinkx/HackHunter'
url_hackathons = 'https://github.com/saypinkx/HackHunter'
url_hackathons2 = 'https://github.com/saypinkx/HackHunter'
